# Generated by Django 5.1.3 on 2024-11-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_T', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='day',
        ),
        migrations.AddField(
            model_name='timetable',
            name='course_code',
            field=models.CharField(blank=True, help_text='Optional course code.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='course_name',
            field=models.CharField(blank=True, help_text='Optional course name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', help_text='Day of the week for the session.', max_length=9),
        ),
        migrations.AddField(
            model_name='timetable',
            name='instructor',
            field=models.CharField(blank=True, help_text='Optional instructor name.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_break',
            field=models.BooleanField(default=False, help_text='Mark as a break or empty slot.'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(help_text='End time of the session.'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, help_text='Optional room number or location.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(help_text='Start time of the session.'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
