# Generated by Django 5.1.3 on 2024-11-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_T', '0002_remove_lecturer_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='course_name',
            field=models.CharField(blank=True, help_text="Optional course name. If not provided, will be considered 'Free'.", max_length=100, null=True),
        ),
    ]
