# Generated by Django 5.1.3 on 2024-11-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_T', '0003_alter_timetable_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_08_00_09_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_09_00_10_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_10_00_11_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_11_00_12_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_12_00_13_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_13_00_14_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_14_00_15_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_15_00_16_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
