# Generated by Django 5.1.3 on 2024-11-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_T', '0004_timetable_day_timetable_time_08_00_09_00_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='time_slots',
            field=models.JSONField(default=dict),
        ),
    ]
