# Generated by Django 5.1.3 on 2024-11-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_T', '0007_timetable_day_alter_timetable_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='time_08_00_09_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_09_00_10_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_10_00_11_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_11_00_12_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_12_00_13_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_13_00_14_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_14_00_15_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_15_00_16_00',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_slots',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', help_text='Day of the week for the session.', max_length=9),
        ),
    ]
